# Generated by Django 3.2.9 on 2022-09-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_auto_20220908_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconstants',
            name='stamp',
        ),
    ]
