# Generated by Django 3.2.9 on 2022-09-04 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None, verbose_name='phone')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('bgcolor', models.CharField(blank=True, default=manager.models.bgcolor, max_length=10, null=True)),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'contact_tbl',
                'db_table': 'contact_tbl',
            },
        ),
        migrations.CreateModel(
            name='ExtendedAdmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('main', models.BooleanField(default=False)),
                ('is_installed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'extended_admins',
                'db_table': 'extended_admin',
            },
        ),
        migrations.CreateModel(
            name='ExtendedAuthUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None, unique=True, verbose_name='phone')),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('bgcolor', models.CharField(blank=True, default=manager.models.bgcolor, max_length=10, null=True)),
                ('company', models.CharField(blank=True, default='Illuminate', max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='profiles/')),
                ('role', models.CharField(blank=True, choices=[('employee', 'Employee'), ('admins', 'Admin')], max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'extended_auth_users',
                'db_table': 'extended_auth_user',
                'permissions': (('can_view', 'Can view'), ('can_edit', 'Can edit'), ('can_see_invoice', 'Can see invoice')),
            },
        ),
        migrations.CreateModel(
            name='GallaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallary/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'gallary_tbl',
                'db_table': 'gallary_tbl',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'category_tbl',
                'db_table': 'category_tbl',
            },
        ),
    ]
