# Generated by Django 3.2.9 on 2022-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='school_id',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
