# Generated by Django 3.2.9 on 2022-09-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_coursemodel_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='school_id',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
