# Generated by Django 3.2.9 on 2022-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_semmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='semmodel',
            name='course_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='semmodel',
            name='course_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
