# Generated by Django 3.2.9 on 2022-09-09 15:51

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20220909_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='stamp',
            field=models.ImageField(blank=True, default='stamp/stamp.png', null=True, upload_to='stamp/'),
        ),
        migrations.AddField(
            model_name='extendedauthuser',
            name='exam_id',
            field=models.CharField(blank=True, default=manager.models.generate_id, max_length=100, null=True),
        ),
    ]
