# Generated by Django 3.2.9 on 2022-09-05 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0007_auto_20220904_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', jsonfield.fields.JSONField(blank=True, null=True)),
                ('service_head', models.CharField(blank=True, max_length=100, null=True)),
                ('service_text', models.TextField(blank=True, null=True)),
                ('archieve_head', models.CharField(blank=True, max_length=100, null=True)),
                ('archieve_text', models.TextField(blank=True, null=True)),
                ('archieve_bg', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('no_year_of_expe', models.IntegerField(blank=True, null=True)),
                ('text_year_of_expe', models.CharField(blank=True, max_length=100, null=True)),
                ('no_happy_children', models.IntegerField(blank=True, null=True)),
                ('text_happy_children', models.CharField(blank=True, max_length=100, null=True)),
                ('no_event', models.IntegerField(blank=True, null=True)),
                ('text_event', models.CharField(blank=True, max_length=100, null=True)),
                ('no_fund_raised', models.IntegerField(blank=True, null=True)),
                ('text_fund_raised', models.CharField(blank=True, max_length=100, null=True)),
                ('team', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'home_tbl',
                'db_table': 'home_tbl',
            },
        ),
    ]
