# Generated by Django 3.2.9 on 2022-09-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20220909_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='student_fee_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
