# Generated by Django 3.2.9 on 2022-09-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20220905_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='team_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
