# Generated by Django 3.2.9 on 2022-09-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_homemodel_team_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='no_event',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='no_happy_children',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='no_year_of_expe',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
