# Generated by Django 3.2.9 on 2022-09-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_extendedauthuser_student_fee_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='nominal_roll',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='fee',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
