# Generated by Django 3.2.9 on 2022-09-05 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_auto_20220905_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1_head', models.CharField(blank=True, max_length=100, null=True)),
                ('slider1_text', models.TextField(blank=True, max_length=100, null=True)),
                ('slider1_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('slider2_head', models.CharField(blank=True, max_length=100, null=True)),
                ('slider2_text', models.TextField(blank=True, max_length=100, null=True)),
                ('slider2_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('slider3_head', models.CharField(blank=True, max_length=100, null=True)),
                ('slider3_text', models.TextField(blank=True, max_length=100, null=True)),
                ('slider3_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'slider_tbl',
                'db_table': 'slider_tbl',
            },
        ),
    ]
