# Generated by Django 3.2.9 on 2022-09-09 22:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_exammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='registered_courses',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
