# Generated by Django 3.2.9 on 2022-09-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_slidermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidermodel',
            old_name='slider1_head',
            new_name='slider_head',
        ),
        migrations.RenameField(
            model_name='slidermodel',
            old_name='slider1_image',
            new_name='slider_image',
        ),
        migrations.RenameField(
            model_name='slidermodel',
            old_name='slider1_text',
            new_name='slider_text',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='slider2_head',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='slider2_image',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='slider2_text',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='slider3_head',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='slider3_image',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='slider3_text',
        ),
    ]
