# Generated by Django 3.2.9 on 2022-09-06 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0013_auto_20220905_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_head', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_text', models.TextField(blank=True, max_length=100, null=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'blogs_tbl',
                'db_table': 'blogs_tbl',
            },
        ),
    ]
