# Generated by Django 3.2.9 on 2022-09-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_extendedauthuser_registered_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='academic_year',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='semmodel',
            name='academic_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
