# Generated by Django 3.2.9 on 2022-09-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20220910_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='academic_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
