# Generated by Django 3.2.9 on 2022-09-06 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_blogsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None, verbose_name='phone')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('bgcolor', models.CharField(blank=True, default=manager.models.bgcolor, max_length=10, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.blogsmodel')),
            ],
            options={
                'verbose_name_plural': 'comment_tbl',
                'db_table': 'comment_tbl',
            },
        ),
    ]
