# Generated by Django 3.2.9 on 2022-09-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_exammodel_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='exammodel',
            name='reg_no',
        ),
        migrations.AlterField(
            model_name='extendedauthuser',
            name='academic_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
