# Generated by Django 3.2.9 on 2022-09-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='subject',
        ),
    ]
