# Generated by Django 3.2.9 on 2022-09-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_remove_commentmodel_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='gallarymodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='AboutModel',
        ),
        migrations.DeleteModel(
            name='BlogsModel',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.DeleteModel(
            name='GallaryModel',
        ),
        migrations.DeleteModel(
            name='HomeModel',
        ),
        migrations.DeleteModel(
            name='ServiceModel',
        ),
        migrations.DeleteModel(
            name='SliderModel',
        ),
    ]
